sequentech/ballot-box

app/controllers/ElectionsApi.scala, app/models/Models.scala, conf/application.conf, conf/evolutions/default/1.sql, conf/evolutions/default/2.sql
Depend on PR https://github.com/agoravoting/agora-gui-admin/pull/2
=> Added real field to Election model.

admin/admin.py, app/commands/Console.scala, app/controllers/BallotboxApi.scala, app/controllers/ElectionsApi.scala, app/utils/Datastore.scala, conf/routes
Improve Voterids Dump command to allow more use-cases and make it faster / scalable and use less RAM.
=> Scalable voterids dump

app/models/Models.scala
* adding election extra flag: disable__election_chooser_screen
* adding also another extra_option: election_success_voted_text
* revert prev commit
=> adding election extra flag: disable__election_chooser_screen

conf/application.conf, conf/logback.xml
* adding date to logs
* configuring properly the logging datetime
* using UTC for logging
=> Timezone support

app/utils/Actions.scala
* allowing for separator chars in the userid
* fix typo
* better printing failures
=> Fix khmac: allowing for separator chars in the userid

build.sbt, pom.xml
Include changes to master from [this PR.](https://github.com/sequentech/ballot-box/pull/130)
=> Bump postgres version (6.1.x)

app/controllers/ElectionsApi.scala
* Fix `calcResultsLogic` so that it returns a future with the result/error.
=> Ballot-box calculate-results not returning error

build.sbt
[Continuation of previous PR](https://github.com/sequentech/ballot-box/pull/142)
=> Bump postgresql from 42.4.1 to 42.4.3

app/controllers/ElectionsApi.scala
fix trustees when there are slave servers
=> Fix trustees list when there are slave servers (#152)

app/models/Models.scala
Parent issue: https://github.com/sequentech/epi/issues/19
=> ✨ Countdown until logout 

app/controllers/BallotboxApi.scala, app/controllers/ElectionsApi.scala, app/utils/Actions.scala, app/utils/Response.scala
Parent issue: https://github.com/sequentech/epi/issues/27
=> ✨different responses on timeout in voting booth

app/models/Models.scala, app/utils/JsonFormatters.scala
Parent issue: https://github.com/sequentech/meta/issues/125
=> ✨ Write-ins multiple fields

app/models/Models.scala, app/utils/JsonFormatters.scala
Parent issue: https://github.com/sequentech/meta/issues/125
=> ✨ Write-ins multiple fields (#171)

app/models/Models.scala
Parent issue: https://github.com/sequentech/meta/issues/122
=> ✨ Multilingualism (#170)

app/models/Models.scala
Parent issue: https://github.com/sequentech/meta/issues/126
=> ✨ Support search/filter candidates feature in voting booth

app/models/Models.scala
Parent issue: https://github.com/sequentech/epi/issues/112
=> ✨ Voting-booth: Improve election info in the ballot ticket PDF for parent-children elections

admin/admin.py
Parent issue: https://github.com/sequentech/meta/issues/124
=> Automated start/stop support

admin/admin.py
Parent issue: https://github.com/sequentech/meta/issues/124
=> Automated start/stop support (#177)

app/models/Models.scala, app/utils/JsonFormatters.scala
Parent issue: https://github.com/sequentech/meta/issues/306
=> ✨ Select languages per election

app/models/Models.scala, app/utils/JsonFormatters.scala
Parent issue: https://github.com/sequentech/meta/issues/306
=> ✨ Select languages per election (#182)

app/models/Models.scala
Parent issue: https://github.com/sequentech/meta/issues/224
=> ✨ Security confirmation

app/models/Models.scala
Parent issue: https://github.com/sequentech/meta/issues/224
=> ✨ Security confirmation (#181)

app/models/Models.scala
Parent issue: https://github.com/sequentech/meta/issues/349
=> 🐞 mandatory_acceptance_tos_html_i18n presentation field should not be mandatory

app/models/Models.scala
Parent issue: https://github.com/sequentech/meta/issues/349
=> 🐞 mandatory_acceptance_tos_html_i18n presentation field should not be  mandatory (#185)

app/models/Models.scala
Parent issue: https://github.com/sequentech/meta/issues/572
=> 🐞 Write-ins config not working

app/models/Models.scala
Parent issue: https://github.com/sequentech/meta/issues/572
=> 🐞 Write-ins config not working (#187)

build.sbt, pom.xml
Parent issue: sequentech/meta#567
Dependabot tickets:
- https://github.com/sequentech/ballot-box/security/dependabot/7
=> Security dependencies update

build.sbt, pom.xml
Parent issue: sequentech/meta#567
Dependabot tickets:
- https://github.com/sequentech/ballot-box/security/dependabot/7
=> Security dependencies update (#191)

app/controllers/ElectionsApi.scala, conf/routes
Parent issue: https://github.com/sequentech/epi/issues/36
=> ✨ Check if the authorities are online (#194)

admin/dump_votes.py
Parent issue: https://github.com/sequentech/meta/issues/552
=> ✨ weighted voting support

admin/dump_votes.py
Parent issue: https://github.com/sequentech/meta/issues/552
=> ✨ weighted voting support (#198)

app/models/Models.scala
Parent issue: https://github.com/sequentech/meta/issues/402
=> 🐞 Trustees struggle to respond to director (#195)

admin/dump_votes.py
Parent issue: https://github.com/sequentech/meta/issues/802
=> 🐞 Dumping of votes dumps only the first vote when not filtering by voter id

.github/workflows/unittests.yml, test/BallotboxSpec.scala, test/ElectionsSpec.scala
Parent issue: https://github.com/sequentech/meta/issues/803
=> 🐞 `ballot-box` unit tests don't compile

app/models/Models.scala, app/utils/JsonFormatters.scala
Parent issue: https://github.com/sequentech/meta/issues/234
=> ✨ Voter eligibility check

app/models/Models.scala, app/utils/JsonFormatters.scala
Parent issue: https://github.com/sequentech/meta/issues/234
=> ✨ Voter eligibility check (#208)

app/models/Models.scala
Parent issue: https://github.com/sequentech/meta/issues/2572
=> ✨ Add field to insert html after a question in the voting/review screens

app/models/Models.scala
Parent issue: https://github.com/sequentech/meta/issues/2572
=> ✨ Add field to insert html after a question in the voting/review screen
